-- Road Song trip-store schema (D1 / SQLite).
--
-- One Trip per row; Memories scoped by trip_id. Every API request carries the
-- trip code; the Worker resolves code -> trip_id and only ever reads/writes
-- rows for that trip, so scope is enforced server-side with no accounts.

CREATE TABLE IF NOT EXISTS trips (
  id            TEXT PRIMARY KEY,            -- uuid, generated by the Worker
  code          TEXT NOT NULL UNIQUE,        -- public trip code from the link (roadsong.app/t/<code>)
  name          TEXT NOT NULL,
  first_day     TEXT NOT NULL DEFAULT '',
  last_day      TEXT NOT NULL DEFAULT '',
  cover_index   INTEGER NOT NULL DEFAULT 0,
  created_at    TEXT NOT NULL                -- ISO-8601 UTC
);

CREATE INDEX IF NOT EXISTS idx_trips_code ON trips (code);

CREATE TABLE IF NOT EXISTS memories (
  id            TEXT PRIMARY KEY,            -- uuid, generated by the Worker
  trip_id       TEXT NOT NULL REFERENCES trips (id) ON DELETE CASCADE,
  type          TEXT NOT NULL CHECK (type IN ('photo', 'video', 'text')),
  contributor   TEXT NOT NULL,               -- display name signed on the memory
  author        TEXT NOT NULL,               -- display handle (e.g. @maya)
  caption       TEXT NOT NULL DEFAULT '',
  text          TEXT NOT NULL DEFAULT '',    -- lore body / note
  day           INTEGER NOT NULL DEFAULT 1,
  day_date      TEXT,                        -- e.g. 'JUN 12'
  location_name TEXT,                        -- optional place pin
  latitude      REAL,                        -- nullable from day one
  longitude     REAL,
  media_key     TEXT,                        -- R2 object key, only for photo/video
  media_url     TEXT,                        -- public media URL when available
  created_at    TEXT NOT NULL                -- ISO-8601 UTC
);

CREATE INDEX IF NOT EXISTS idx_memories_trip_created
  ON memories (trip_id, created_at);
