#!/usr/bin/env python3
"""Generate the bundled vibe-audition audio for Road Song (issue #29).

Each vibe gets a short (~8 s), audibly distinct instrumental loop synthesized
from scratch — no samples, no network — and encoded to MP3 so it plays on
iOS, Android and web through audioplayers AssetSource. The audio is
royalty-free by construction: generated by this repo's own script (see
assets/audio/vibes/PROVENANCE.md).

Requires Python 3 and ffmpeg on PATH.
Usage: python3 tool/generate_vibe_audio.py
"""

import math
import os
import random
import struct
import subprocess
import wave

SAMPLE_RATE = 22050
DURATION_S = 8.0
OUT_DIR = os.path.join('assets', 'audio', 'vibes')


def freq(midi_note):
    return 440.0 * (2.0 ** ((midi_note - 69) / 12.0))


def midi(name):
    names = {'C': 0, 'C#': 1, 'D': 2, 'D#': 3, 'E': 4, 'F': 5,
             'F#': 6, 'G': 7, 'G#': 8, 'A': 9, 'A#': 10, 'B': 11}
    return 12 * (int(name[-1]) + 1) + names[name[:-1]]


def sine(t, f):
    return math.sin(2 * math.pi * f * t)


def square(t, f):
    return 1.0 if math.sin(2 * math.pi * f * t) >= 0 else -1.0


def saw(t, f):
    return 2.0 * ((f * t) % 1.0) - 1.0


def triangle(t, f):
    return 4.0 * abs(((f * t) % 1.0) - 0.5) - 1.0


WAVES = {'sine': sine, 'square': square, 'saw': saw, 'triangle': triangle}

# Chord tones (semitone offsets from the key): I, IV, V, vi.
CHORDS = [0, 5, 7, 9]

# One vibe per catalog entry: tempo, key center, lead/bass timbres, a
# 16-step (two bars of 8th notes) lead pattern, and drum layers. Distinct
# tempo, key and timbre per vibe so auditions are clearly different.
VIBES = {
    'pop_punk': dict(bpm=168, key=midi('A2'), lead='square', bass='square',
                     pattern=[1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1],
                     kick=True, hats=False),
    'euro_trash_synth': dict(bpm=128, key=midi('F2'), lead='saw', bass='saw',
                             pattern=[1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1],
                             kick=True, hats=True),
    'sad_boy_indie': dict(bpm=92, key=midi('E3'), lead='triangle', bass='sine',
                          pattern=[1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
                          kick=False, hats=False),
    'acoustic_road_folk': dict(bpm=104, key=midi('G2'), lead='triangle', bass='sine',
                               pattern=[1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
                               kick=False, hats=False),
    'chaotic_rap': dict(bpm=144, key=midi('D2'), lead='saw', bass='square',
                        pattern=[1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1],
                        kick=True, hats=True),
}


def render(name, spec):
    bpm = spec['bpm']
    key = spec['key']
    lead = WAVES[spec['lead']]
    bass = WAVES[spec['bass']]
    pattern = spec['pattern']
    beat = 60.0 / bpm
    step = beat / 2.0
    total = int(SAMPLE_RATE * DURATION_S)
    rng = random.Random(0)
    out = [0.0] * total

    for i in range(total):
        t = i / SAMPLE_RATE
        step_index = int(t / step)
        chord = CHORDS[(step_index // 4) % len(CHORDS)]
        if pattern[step_index % len(pattern)]:
            out[i] += 0.15 * lead(t, freq(key + 24 + chord))
        beat_index = int(t / beat)
        out[i] += 0.20 * bass(
            t, freq(key - 12 + CHORDS[(beat_index // 2) % len(CHORDS)]))
        if spec['kick']:
            within = t % beat
            if within < 0.12:
                env = 1.0 - within / 0.12
                out[i] += 0.45 * env * math.sin(
                    2 * math.pi * (95 - 50 * within / 0.12) * t)
        if spec['hats']:
            within = t % step
            if within < 0.03:
                env = 1.0 - within / 0.03
                out[i] += 0.08 * env * (2.0 * rng.random() - 1.0)

    # Fade in/out to avoid clicks at the loop edges.
    fade_in = int(0.05 * SAMPLE_RATE)
    fade_out = int(0.5 * SAMPLE_RATE)
    for i in range(total):
        if i < fade_in:
            out[i] *= i / fade_in
        if i >= total - fade_out:
            out[i] *= (total - i) / fade_out

    peak = max(1e-9, max(abs(s) for s in out))
    scale = 0.9 / peak
    return [max(-1.0, min(1.0, s * scale)) for s in out]


def write_wav(path, samples):
    with wave.open(path, 'w') as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(SAMPLE_RATE)
        w.writeframes(b''.join(
            struct.pack('<h', int(s * 32767)) for s in samples))


def encode_mp3(wav_path, mp3_path):
    subprocess.run(
        ['ffmpeg', '-y', '-loglevel', 'error', '-i', wav_path,
         '-codec:a', 'libmp3lame', '-b:a', '96k', '-ar', str(SAMPLE_RATE),
         '-ac', '1', mp3_path],
        check=True,
    )


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    for name, spec in VIBES.items():
        wav = os.path.join(OUT_DIR, name + '.wav')
        mp3 = os.path.join(OUT_DIR, name + '.mp3')
        write_wav(wav, render(name, spec))
        encode_mp3(wav, mp3)
        os.remove(wav)
        size = os.path.getsize(mp3)
        print(f'{mp3}: {size // 1024} KiB')


if __name__ == '__main__':
    main()
